### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by CristiRO** [meln1k/akka-persistence-foundationdb#1]
Hello!
I've cloned the repository and run `test` command in sbt console. Unfortunately, only 3 test suites out of 8 are passing, the other ones giving same error:
```
[info] FoundationDbJournalPerfSpec:
[info] akka.persistence.foundationdb.journal.FoundationDbJournalPerfSpec *** ABORTED ***
[info]   com.apple.foundationdb.FDBException: API version may be set only once
[info]   at com.apple.foundationdb.FDB.Select_API_version(Native Method)
[info]   at com.apple.foundationdb.FDB.selectAPIVersion(FDB.java:187)
[info]   at akka.persistence.foundationdb.FdbConnection$.fdb$lzycompute(FoundationDbLifecycle.scala:113)
[info]   at akka.persistence.foundationdb.FdbConnection$.fdb(FoundationDbLifecycle.scala:112)
[info]   at akka.persistence.foundationdb.FdbConnection$.cluster$lzycompute(FoundationDbLifecycle.scala:116)
[info]   at akka.persistence.foundationdb.FdbConnection$.cluster(FoundationDbLifecycle.scala:115)
[info]   at akka.persistence.foundationdb.FoundationDbLifecycle.db(FoundationDbLifecycle.scala:79)
[info]   at akka.persistence.foundationdb.FoundationDbLifecycle.db$(FoundationDbLifecycle.scala:79)
[info]   at akka.persistence.foundationdb.journal.FoundationDbJournalPerfSpec.db$lzycompute(FoundationDbJournalSpec.scala:70)
[info]   at akka.persistence.foundationdb.journal.FoundationDbJournalPerfSpec.db(FoundationDbJournalSpec.scala:70)
```
Is it a problem with tests or the plugin itself?

**Comment by meln1k** [comment]
Hi @CristiRO, I think the problem here is that FoundationDB client creates native bindings that live until JVM is stopped. So once we finish running a test, those connection objects are being kept in memory and that creates problems when we initialize the client twice. The workaround here is to restart sbt before calling the `test` command. The proper solution is to fork JVM before running tests, I'll provide a fix soon.

**Comment by meln1k** [comment]
I've fixed it in the recent commit.
